### ISSUE TITLE
Procfile

### ISSUE THREAD

**Issue by acook** [base698/tmux-copy-paste-mac-osx#1]
Instead of grepping the process list a Profile would be much safer/saner.

**Comment by base698** [comment]
Yep.  I got this to work really quick, but found it insufficient if I wanted the + register to work as designed in vim.  Alas, I went back to reattach-user-namespace.  If you were using it I'll merge any changes you want.

Cheers

**Comment by acook** [comment]
Ah okay, I'll keep it in mind.

I understand though. It took me a while to figure out what the problem was. It's all really frustrating.

I [set up a keybinding](https://github.com/acook/config/blob/master/dotfiles/.tmux.conf#L109-L112) to push/pull the system clipboard manually, but I'm not thrilled with it.
